[tool.bumpversion]
message = "Bump version: {current_version} → {new_version}"

parse = """(?x)
    (?P<release>                    # The release part
        (?:[1-9][0-9]{3})\\.        # YYYY.
        (?:1[0-2]|[1-9])            # MM
    )
    (?:\\.(?P<patch>\\d+))?         # .patch, optional
    (?:dev                          # pre-release label
        (?P<pre>0|[1-9]\\d*)        # pre-release version number
    )?                              # pre-release section is optional
"""

serialize = [
   "{release}.{patch}dev{pre}",
   "{release}dev{pre}",
   "{release}.{patch}",
   "{release}",
]

[tool.bumpversion.parts.release]
calver_format = "{YYYY}.{MM}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

